# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Desktop/kokoro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Desktop/kokoro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/kokoro/CMakeFiles /home/user/Desktop/kokoro//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/kokoro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kokoro_tts

# Build rule for target.
kokoro_tts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kokoro_tts
.PHONY : kokoro_tts

# fast build rule for target.
kokoro_tts/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/build
.PHONY : kokoro_tts/fast

src/audio/wav_writer.o: src/audio/wav_writer.cpp.o
.PHONY : src/audio/wav_writer.o

# target to build an object file
src/audio/wav_writer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/audio/wav_writer.cpp.o
.PHONY : src/audio/wav_writer.cpp.o

src/audio/wav_writer.i: src/audio/wav_writer.cpp.i
.PHONY : src/audio/wav_writer.i

# target to preprocess a source file
src/audio/wav_writer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/audio/wav_writer.cpp.i
.PHONY : src/audio/wav_writer.cpp.i

src/audio/wav_writer.s: src/audio/wav_writer.cpp.s
.PHONY : src/audio/wav_writer.s

# target to generate assembly for a file
src/audio/wav_writer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/audio/wav_writer.cpp.s
.PHONY : src/audio/wav_writer.cpp.s

src/kokoro/kokoro_tts.o: src/kokoro/kokoro_tts.cpp.o
.PHONY : src/kokoro/kokoro_tts.o

# target to build an object file
src/kokoro/kokoro_tts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/kokoro/kokoro_tts.cpp.o
.PHONY : src/kokoro/kokoro_tts.cpp.o

src/kokoro/kokoro_tts.i: src/kokoro/kokoro_tts.cpp.i
.PHONY : src/kokoro/kokoro_tts.i

# target to preprocess a source file
src/kokoro/kokoro_tts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/kokoro/kokoro_tts.cpp.i
.PHONY : src/kokoro/kokoro_tts.cpp.i

src/kokoro/kokoro_tts.s: src/kokoro/kokoro_tts.cpp.s
.PHONY : src/kokoro/kokoro_tts.s

# target to generate assembly for a file
src/kokoro/kokoro_tts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/kokoro/kokoro_tts.cpp.s
.PHONY : src/kokoro/kokoro_tts.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/misaki/cmudict.o: src/misaki/cmudict.cpp.o
.PHONY : src/misaki/cmudict.o

# target to build an object file
src/misaki/cmudict.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/cmudict.cpp.o
.PHONY : src/misaki/cmudict.cpp.o

src/misaki/cmudict.i: src/misaki/cmudict.cpp.i
.PHONY : src/misaki/cmudict.i

# target to preprocess a source file
src/misaki/cmudict.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/cmudict.cpp.i
.PHONY : src/misaki/cmudict.cpp.i

src/misaki/cmudict.s: src/misaki/cmudict.cpp.s
.PHONY : src/misaki/cmudict.s

# target to generate assembly for a file
src/misaki/cmudict.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/cmudict.cpp.s
.PHONY : src/misaki/cmudict.cpp.s

src/misaki/g2p.o: src/misaki/g2p.cpp.o
.PHONY : src/misaki/g2p.o

# target to build an object file
src/misaki/g2p.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/g2p.cpp.o
.PHONY : src/misaki/g2p.cpp.o

src/misaki/g2p.i: src/misaki/g2p.cpp.i
.PHONY : src/misaki/g2p.i

# target to preprocess a source file
src/misaki/g2p.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/g2p.cpp.i
.PHONY : src/misaki/g2p.cpp.i

src/misaki/g2p.s: src/misaki/g2p.cpp.s
.PHONY : src/misaki/g2p.s

# target to generate assembly for a file
src/misaki/g2p.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/g2p.cpp.s
.PHONY : src/misaki/g2p.cpp.s

src/misaki/text_normalizer.o: src/misaki/text_normalizer.cpp.o
.PHONY : src/misaki/text_normalizer.o

# target to build an object file
src/misaki/text_normalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/text_normalizer.cpp.o
.PHONY : src/misaki/text_normalizer.cpp.o

src/misaki/text_normalizer.i: src/misaki/text_normalizer.cpp.i
.PHONY : src/misaki/text_normalizer.i

# target to preprocess a source file
src/misaki/text_normalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/text_normalizer.cpp.i
.PHONY : src/misaki/text_normalizer.cpp.i

src/misaki/text_normalizer.s: src/misaki/text_normalizer.cpp.s
.PHONY : src/misaki/text_normalizer.s

# target to generate assembly for a file
src/misaki/text_normalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/text_normalizer.cpp.s
.PHONY : src/misaki/text_normalizer.cpp.s

src/misaki/tokenizer.o: src/misaki/tokenizer.cpp.o
.PHONY : src/misaki/tokenizer.o

# target to build an object file
src/misaki/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/tokenizer.cpp.o
.PHONY : src/misaki/tokenizer.cpp.o

src/misaki/tokenizer.i: src/misaki/tokenizer.cpp.i
.PHONY : src/misaki/tokenizer.i

# target to preprocess a source file
src/misaki/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/tokenizer.cpp.i
.PHONY : src/misaki/tokenizer.cpp.i

src/misaki/tokenizer.s: src/misaki/tokenizer.cpp.s
.PHONY : src/misaki/tokenizer.s

# target to generate assembly for a file
src/misaki/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kokoro_tts.dir/build.make CMakeFiles/kokoro_tts.dir/src/misaki/tokenizer.cpp.s
.PHONY : src/misaki/tokenizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kokoro_tts"
	@echo "... src/audio/wav_writer.o"
	@echo "... src/audio/wav_writer.i"
	@echo "... src/audio/wav_writer.s"
	@echo "... src/kokoro/kokoro_tts.o"
	@echo "... src/kokoro/kokoro_tts.i"
	@echo "... src/kokoro/kokoro_tts.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/misaki/cmudict.o"
	@echo "... src/misaki/cmudict.i"
	@echo "... src/misaki/cmudict.s"
	@echo "... src/misaki/g2p.o"
	@echo "... src/misaki/g2p.i"
	@echo "... src/misaki/g2p.s"
	@echo "... src/misaki/text_normalizer.o"
	@echo "... src/misaki/text_normalizer.i"
	@echo "... src/misaki/text_normalizer.s"
	@echo "... src/misaki/tokenizer.o"
	@echo "... src/misaki/tokenizer.i"
	@echo "... src/misaki/tokenizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

